name: ci

on:
  push:
    branches:
      - master

jobs:
  docker-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/gateway:latest,ghcr.io/${{ github.repository }}/gateway:${{ github.sha }}

      # Kubernetes deployment
      - uses: actions/checkout@master
      - name: Run commands on the pod
        uses: danielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: exec deployment/gateway -- /bin/sh -c 'git pull && iex --name recompile@${POD_IP} --cookie dstn --remsh gateway --rpc-eval gateway "IEx.Helpers.recompile()" -e ":erlang.halt"'
